#!/usr/bin/env bash

### BEGIN INIT INFO
# Provides: 	wifi-route	
# Required-Start: network-manager
# Should-Start:		$network
# Should-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:  wifi route feature
# Description:   wifi route
#			Authenticator
### END INIT INFO

startup()
{
    nmcli nm wifi off
    rfkill unblock wifi
    ifconfig wlan0 up
    ifconfig wlan0 192.168.15.1
    iptables -t nat -F
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    sysctl net.ipv4.ip_forward=1
    service dnsmasq restart
    service hostapd restart
}

stop_()
{
    service dnsmasq stop
    service hostapd stop
    iptables -t nat -F
    sysctl net.ipv4.ip_forward=0
    rfkill block wifi
}

[ -f /tmp/log ] || sleep 20
echo "$(date) run wifi-route $1" >> /tmp/log
case "$1" in
    start  ) 
        startup
        ;;
    stop   )
        stop_
        ;;
    restart) 
         startup
        ;;
    *    ) echo "Usage: $0 (start|stop|restart)" ;;
esac
exit 0
