#!/bin/sh

### BEGIN INIT INFO
# Provides: 	wifi-route	
# Required-Start: network-manager
# Should-Start:		$network
# Should-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:  wifi route feature
# Description:   wifi route
#			Authenticator
### END INIT INFO

startup()
{
    # Open wlan0
    rfkill unblock wifi
    ifconfig wlan0 up
    # Set wlan0 ip address
    ifconfig wlan0 192.168.15.1
    # Configure NAT
    # Delete NAT rules
    iptables -t nat -F
    # Add NAT rule
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    # Enable ip forwoad
    sysctl net.ipv4.ip_forward=1
    # start services
    service dnsmasq start
    service hostapd start
    rfkill unblock wifi 
}

stop_()
{
    # Stop services
    service dnsmasq stop
    service hostapd stop
    # Delete NAT Setting
    iptables -t nat -F
    # Disable ip forward
    sysctl net.ipv4.ip_forward=0
}

echo "$(date) run wifi-route $1" >> /tmp/log
case "$1" in
    start  ) 
        startup
        ;;
    stop   )
        stop_
        ;;
    restart) 
         stop_
         startup
        ;;
    *    ) echo "Usage: $0 (start|stop|restart)" ;;
esac
exit 0
