#java
export JAVA_HOME="$(/usr/libexec/java_home)"

#hadoop
export HADOOP_HOME="/Users/$(whoami)/devel/hadoop-2.6.0"
export PATH="$PATH:$HADOOP_HOME/bin"

#ANT
ANT_HOME="/Users/$(whoami)/devel/apache-ant-1.9.4" 
export PATH="$PATH:$ANT_HOME/bin" 
#maven
export M2_HOME="/Users/$(whoami)/devel/apache-maven-3.2.5"
export PATH="$PATH:$M2_HOME/bin"
export MAVEN_OPTS="-Xms256m -Xmx512m"
