#java
export JAVA_HOME="/usr/lib/jvm/default-java"
export CLASSPATH=".:$JAVA_HOME/lib:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/toolsi.jar" 
export PATH="$JAVA_HOME/bin:$PATH"

#hadoop
export HADOOP_INSTALL="/home/$(whoami)/devel/hadoop-2.6.0"
export PATH="$PATH:$HADOOP_INSTALL/bin"

#maven
export M2_HOME="/home/$(whoami)/devel/apache-maven-3.2.5"  
export PATH="$PATH:$M2_HOME/bin"
export MAVEN_OPTS="-Xms256m -Xmx512m" 

#tmp
export PYTHONPATH=${PYTHONPATH}:"/home/xouyang/devel/qpid-proton-0.8"
