#!/bin/bash

#set +e

USER=$(whoami)
if [ "$USER" == "root" ]; then
  D_HOME=/home/user   #bluebird
else
  D_HOME=/home/$USER
fi
source $D_HOME/customize/include/func.sh

insapp vim
insapp sshfs
insapp git
insapp screen

which myscp 2>&1 > /dev/null || $D_HOME/customize/tools/sshLink.py

alias vi=vim
