#!/usr/bin/env bash
F_T="./.types"

f_src="./src.files"

if [ ! -f "$F_T" ]; then
    echo "NOT define types file \"$F_T\""
    exit 1
fi

declare -a types
while read line; do
    types=(${types[@]} ${line[@]})
done <"$F_T"

len=${#types[@]}
if [ $len -lt 1 ]; then
    echo 'NOT define types in \"$F_T\"'
    exit 2
fi

args="-name ${types[0]}"

if [ $len -gt 1 ]; then
    for i in ${types[@]:1}; do
        args="$args -o -name $i"
    done
fi

echo $args
find ./ $args > $f_src
f_tag=$(which ctags)
#"$f_tag" --c++-kinds=+px --fields=+iaS --extra=+q -L $f_src
"$f_tag" -I __THROW -I __attribute_pure__ -I __nonnull -I __attribute__ --file-scope=yes \
    --languages=c,c++ --links=yes --c-kinds=+p --c++-kinds=+p --fields=+iaS \
    --extra=+q -L $f_src

f_cs=$(which cscope)
"$f_cs" -bkq -i $f_src
#"$f_cs" -Rbkq $f_src
rm -f $f_src

## EOF
