set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vimrcs/bundle/Vundle.vim
call vundle#begin()
source ~/.vimrcs/vundle.vim
call vundle#end()            " required

source ~/.vimrcs/basic.vim
source ~/.vimrcs/plugins_cfg.vim
source ~/.vimrcs/filetypes.vim
source ~/.vimrcs/shutcut.vim
source ~/.vimrcs/extended.vim
source ~/.vimrcs/cscope_maps.vim
