#!/bin/bash

#set +e

USER=$(whoami)
if [ "$USER" == "root" ]; then
  D_HOME=/home/user   #bluebird
else
  D_HOME=/home/$USER
fi
source $D_HOME/customize/func.sh


OS=
which yum 2>&1 >/dev/null && OS=F
if [ "X$OS" == "X" ]; then
  insapp python-pexpect
else
  insapp pexpect
fi
