#!/bin/bash
VERSION="2.0.3"
set -e
wget http://luajit.org/download/LuaJIT-$VERSION.tar.gz
tar zxvf LuaJIT-$VERSION.tar.gz
cd LuaJIT-$VERSION
make && sudo make install
cd ../ && rm -rf LuaJIT*
USER_N=$(whoami)
[ "$USER_N" == "root" ] && USER_N=user
F="/home/$USER_N/customize/env_init/bluebird"
touch $F
echo "LUAJIT_LIB=/usr/local/lib" >> $F
echo "LUAJIT_INC=/usr/local/include/luajit-2.0" >> $F


