#!/usr/bin/env bash
alias xstart="startx /etc/X11/Xsession /usr/bin/kodi-standalone"
alias ustart="startx /etc/X11/Xsession /usr/bin/startxbmcbuntu"

alias connecter="cat /var/lib/misc/dnsmasq.leases"

alias ls="ls --color"
